apiVersion: v1
kind: Service
metadata:
  name: {{ include "libhelm.fullname" . }}
  labels:
    {{- include "libhelm.labels" . | nindent 4 }}
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8000"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsport }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "libhelm.selectorLabels" . | nindent 4 }}
